# Generated by Django 2.2.7 on 2019-11-17 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
